language: node_js
services: mongodb
node_js:
  - "8.11.3"
install:
  - npm i
before_script:
  - mongo localhost/newBlog db.default.js
script:
  - npm run lint
  - touch static/favicon.png # Create a dummy favicon
  - cp config.sample.ts config.ts
  - sed -i 's,https://new.ntzyz.cn,http://localhost:1234,g' config.ts
  - npm run build
  - npm run test
after_script:
  - npm run cover
