name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Launch MongoDB
      run: sudo docker run --name mongo -d -p 27017:27017 mongo
    - name: Import initial database
      run: sudo docker container exec -it mongo localhost/newBlog db.default.js
    - name: npm install, build, and test
      run: |
        npm run lint
        cp config.sample.ts config.ts
        sed -i 's,https://new.ntzyz.cn,http://localhost:1234,g' config.ts
        npm run build
        npm run test
      env:
        CI: true
    - name: report coverage
      run: npm run cover
