name: Continuous integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x]
        mongo-version: ['3.6', '4.0', '4.2']

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Launch MongoDB
      run: |
        sudo docker container run --name mongo -v $PWD:/src -p 27017:27017 -d mongo:$MONGO_VERSION
        sleep 4s
      env:
        MONGO_VERSION: ${{ matrix.mongo-version }}
    - name: Import initial database
      run: |
        sudo docker container ls --all
        sudo docker container exec mongo mongo localhost/newBlog /src/db.default.js
    - name: npm install, build, and test
      run: |
        npm install
        npm run lint
        cp config.sample.ts config.ts
        sed -i 's,https://new.ntzyz.cn,http://localhost:1234,g' config.ts
        npm run build
        npm run test
        npx nyc report --reporter=text-lcov
      env:
        CI: true
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
